
CREATE TABLE public.shipping (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	protocol uuid DEFAULT uuidv4() NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz NULL,
	finished_at timestamptz NULL,
	origin varchar NOT NULL,
	destination varchar NOT NULL,
	CONSTRAINT shipping_pk PRIMARY KEY (id),
	CONSTRAINT shipping_unique UNIQUE (protocol)
);